const TodoOps = {
  TODO_INIT: 'TODO_INIT',
  TODO_ADD: 'TODO_ADD',
  TODO_UPDATE: 'TODO_UPDATE',
  TODO_DEL: 'TODO_DEL',
  FUNC: 'FUNC',
  LOADING_SET: 'LOADING_SET',

  AUTH_SET: 'AUTH_SET',
  USER_SET: 'USER_SET',
  AUTH_REFRESH: 'AUTH_REFRESH',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  UPDATE_USER: 'UPDATE_USER',
  REFRESH_USER: 'REFRESH_USER',
  UPDATE_USER_NAME: 'UPDATE_USER_NAME',
  UPDATE_USER_AVATAR: 'UPDATE_USER_AVATAR',
  UPDATE_USER_SURNAME: 'UPDATE_USER_SURNAME',
  UPDATE_USER_BIO: 'UPDATE_USER_BIO',
};

export default TodoOps;
